### ISSUE TITLE
[BUG] Advanced Search API sometimes will not show 1:1 text match as the 1st result.

### ISSUE THREAD

**Issue by ohcello** [ror-community/ror-roadmap#101]
For example:  In the API Call - 

https://api.ror.org/organizations?query.advanced=Atomic%20Energy%20and%20Alternative%20Energies%20Commission

 “Atomic Energy and Alternative Energies Commission”  is a 1:1 text Name match of https://ror.org/00jjx8s55 .  

However, the Advanced Search produces the first output of “National Center of Human Genomics Research”, ( https://ror.org/004yvsb77 ), which is one of many children of Atomic Energy and Alternative Energies Commission.

**Comment by lizkrznarich** [comment]
@ohcello This first result https://ror.org/004yvsb77 does have an exact match to Atomic Energy and Alternative Energies Commission in the relationships.label field, so this is not an invalid result. Query.advanced does not prioritize matches in name or any other field. If you are looking for matches in particular fields, specify those fields in your ?query.advanced search. Alternately, if you are looking for matches only in name fields (name, aliases, labels, acronyms), use the ?query parameter search (which limits results to matches in those fields, plus external IDs). Note that ?query has some fuzziness built in while ?query.advanced does not.

Examples:
https://api.ror.org/organizations?query.advanced=name:Atomic%20Energy%20and%20Alternative%20Energies%20Commission

https://api.ror.org/organizations?query=Atomic%20Energy%20and%20Alternative%20Energies%20Commission

**Comment by ohcello** [comment]
Hello, I did not say the result was invalid, but rather that the ranking/prioritization of matches in name is not what I would consider intuitive considering that the exact text match is included in the results, but just in the middle of the list an not 1st on the list of results.   My suggestion is that, if possible, the logic of Advanced API be modified to always return a 1:1 text name match as the 1st result, but that's just my opinion of what would be expected from *any* search or API Call, Advanced or otherwise.    Thank you for your response.

**Comment by ohcello** [comment]
I understand the match is in the relationship section, as it's the parent of the child that is returned 1st in the list (National Center of Human Genomics Research).  I also understand when you say "query.advanced does not prioritize based on the field that an exact match may be included in".  I'm making a suggestion that if you are going to include the exact text match of the initial Query within the API call results, not in the relationship section, (which you do in this instance and likely all other instances where there is a 1:1 text match), I think it would be expected and preferable to have that 1:1 match listed 1st in the result set.  Some API calls I make only have the capability to pull the 1st result for performance purposes, and yes, I can and will continue to use the other API Query types ROR offers (?query, primarily).  However, this is just my opinion on how you could improve the Advanced API call without changing the contents of the result set (just the ranking/order). I understand if you/ROR/others disagree or do not want to pursue any changes to the existing logic/capabilities.  Thanks again.

**Comment by lizkrznarich** [comment]
@ohcello Thanks for the clarification. For the time being, for internal and external research purposes, we're avoiding prioritizing particular fields or doing any pre/post filtering in ?query.advanced . We _have_ been making incremental changes to ?query and ?affiliation to reorder/filter results as we learn more about integrators' specific use cases (ex: ?affiliation does now prioritize exact matches in name fields), and we are much more open to adjusting those search services at the moment.

**Comment by ohcello** [comment]
ok thanks for the information.  I have notice the improvement in the Affilation calls for sure, however for my Use Cases (usually only reviewing the 1st result), the ?query call (using Name, Country Code) produces the best/most accurate results with the most matches.
