### ISSUE TITLE
[BUG] ROR site preserves data across records when a new ROR ID is entered in the search bar

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#113]
**Describe the bug**
Data in the relationships and external identifier fields persists when you search for a new ID from a given record page, causing the new record page to display erroneous data in these fields

**To Reproduce**
1. Open the page for an existing ROR record
2. Click in the search box
3. Enter the ROR ID for another record and press enter
4. External IDs and relationships from previous record persist on the newly opened

**Expected behavior**
Data appearing on the record page corresponds to it.

**Screenshots**

https://user-images.githubusercontent.com/5152876/206236245-a8fe4ded-88fa-4582-a56c-63ce072f6e5e.mov

**Device information:**
 - Laptop
 - OS: MacOS Ventura 13.0
 - Browser: Firefox 
 - Version: 107.0.1

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-app/releases
