### ISSUE TITLE
[ROADMAP] Optimize community-based curation workflow

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#135]
ROR curation requests have grown in tandem with use of the service and as the registry has achieved independence from GRID. 

ROR relies on a community-based process, leveraging a volunteer curation advisory board, to receive and review requests to add and update registry records. Board members also help to develop and reinforce ROR metadata policies, inclusion criteria, and curation practices, and they provide expertise on specific organization types, regions, and use cases. 

As curation requests increase, we need to ensure that our processes can scale accordingly while maintaining sufficient metadata quality and community involvement. We need to evaluate the current workflow and identify how it might be adjusted, such as expanding participation  of community curators, expediting request processing, etc.

**Comment by lizkrznarich** [comment]
New members have been added to the [curation advisory board](https://ror.org/registry/#curation-advisory-board), and ROR is in the process of hiring part-time curation support contractors.
