### ISSUE TITLE
[ROADMAP] Optimize community onboarding process

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#136]
ROR has an active community and provides many ways for community stakeholders to get involved and stay in the loop. However, the pipeline for onboarding new community members and sharing communications currently takes place across multiple platforms and it can be confusing to know where to start, where to look, and how to keep track of everything. We want to rationalize the onboarding process and make community activity more visible to those who are part of it and those who have not yet joined.

**Comment by amandafrench** [comment]
We've created a new [ROR Community Forum](https://groups.google.com/a/ror.org/g/ror-community) that people can self-join and whose activities are available on the open web, streamlining the processes by which interested people get involved with ROR.
