### ISSUE TITLE
[ROADMAP] Develop guidance for repository integrations

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#137]
ROR integrations in institutional repositories represent a strategic opportunity for driving adoption. We will be pursuing various initiatives to support repository integrations, including developing guidance, holding a virtual workshop, collaborating with pilot integrators on validating guidance, and potentially holding an in-person event at the Open Repositories conference.

**Comment by amandafrench** [comment]
This is complete. Our guidance for repositories, developed in conjunction with over 20 repository representatives, is published at https://zenodo.org/doi/10.5281/zenodo.10049153. Our materials from the Open Repositories workshop is available at https://zenodo.org/doi/10.5281/zenodo.8074995. Additionally, the slides and recording for the Community Showcase presentation by the GREI ROR implementation group are available at https://ror.org/events/2024-01-30-community-showcase/.
