### ISSUE TITLE
[SCHEMA] Add "funder" as an organization type value

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-roadmap#159]
**Describe the problem you would like to solve**
As we reconcile the ROR registry with the Funder Registry, we will need a "funder" type of organization. 

**Describe the schema change that you would like in order to solve the problem**
"Funder" as an additional type in organizational type values, which is already an array and so supports multiple types for one organization. 

**Who would benefit from this change?**
Funders, users of the Funder Registry

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by adambuttrick** [comment]
Request for this functionality in https://github.com/ror-community/ror-updates/issues/2837

**Comment by mariagould** [comment]
Just making a note here that the "funder" organization type will be available in v.2 of the ROR schema, forthcoming (see https://ror.readme.io/docs/schema-v20 for more details)

**Comment by adambuttrick** [comment]
Added with the release of schema v2.0.
