### ISSUE TITLE
[ROADMAP] Typeahead guidelines for ROR adopters

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#16]
**Description:**
Many ROR integrators are interested in implementing typeaheads to help users identify and select affiliations. We are collecting community feedback on use cases and challenges with regard to typeaheads, and will be publishing guidance on best practices.  

**Work related to this roadmap item:**
- [ Feedback document](https://docs.google.com/document/d/1cTf6OBjgHfmij1kgMXKgPon1codmTBl4F1PmmXnFYlU/edit#heading=h.ov1nv77ts7jj)
- [Initial guidance on ROR support site](https://ror.readme.io/docs/create-affiliation-selection-dropdowntypeahead-widgets)

**Comment by lizkrznarich** [comment]
Documentation available at https://ror.readme.io/docs/create-ror-powered-typeaheads
