### ISSUE TITLE
[BUG] Advanced search fails to return results for external_ids.Fundref.preferred and external_ids.Fundref.all

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#179]
**Describe the bug**
Using query.advanced, external_ids.Fundref.preferred and external_ids.Fundref.all fail to return records where a Funder ID is correctly identified/supplied.

**To Reproduce**
1. curl 'https://api.ror.org/organizations?query.advanced=external_ids.Fundref.preferred:100007231' -> 0 results
2. curl 'https://api.ror.org/organizations?query.advanced=external_ids.Fundref.all:100007231' -> 0 results
3. curl 'https://api.ror.org/organizations?query=%22100007231%22' -> returns record

**Expected behavior**
Record(s) with corresponding Funder ID should be returned.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-api/pull/354
