### ISSUE TITLE
Capture insights on user activity on ROR website

### ISSUE THREAD

**Issue by ynnig** [ror-community/ror-roadmap#225]
We would like to have better insights into how users interact with the ROR website in order to understand things like traffic data by page, how users end up at the ROR site, and where users are located. 

Liz has set up some basic logging from Cloudfront into Datadog. We have also discussed using Matomo in the past. We should determine if the Cloudfront logging is sufficient and if not, identify what else would be needed to keep track of website usage on an ongoing basis.

**Comment by amandafrench** [comment]
Resolved with ror-community/ror-site/pull/121
