### ISSUE TITLE
[BUG] Last modified dates incorrect for records updated by actions

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#237]
**Version**
v2.0

**Describe the bug**

Records updated by the create relationships and update labels in related actions do not have their last updated dates correctly populated.

**To Reproduce**
1. Go to https://api.ror.org/v2/organizations/https://ror.org/01ej9dk98, which was updated by create relationships in release v1.45.
2. Review last modified date
3. Date is set as "2023-12-07" vs. "2024-04-05" when the record was updated.

**Expected behavior**
Last modified date should be updated relative to action or a separate action run as part of the release process.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-updates/pull/10799
