### ISSUE TITLE
[MAINTENANCE] Minor updates to data dump description in Zenodo

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#241]
**Summary:**
The standard description for the data dump that is populated automatically in Zenodo when new data dump is published should be modified to fix a few minor typos and add information about licensing with regard to GeoNames location data. The proposed new text is below. 

**Updated text for Zenodo:**

Data dump from the Research Organization Registry (ROR), a community-led registry of open identifiers for research organizations.

Release v1.46 contains ROR IDs and metadata for 109,355 research organizations in JSON and CSV format. This includes the addition of 214 new records and metadata updates to 308 existing records. [See the release notes](https://github.com/ror-community/ror-updates/releases/tag/v1.46).

Beginning with its [March 2022 release](https://doi.org/10.5281/zenodo.6347575), ROR is curated independently from GRID. Semantic versioning beginning with v1.0 was added to reflect this departure from GRID. The existing data structure was not changed.

From March 2022 onward, data releases are versioned as follows:

Minor versions (ex 1.1, 1.2, 1.3): Contain changes to data, such as a new records and updates to existing records. No changes to the data model/structure.
Patch versions (ex 1.0.1): Used infrequently to correct errors in a release. No changes to the data model/structure.
Major versions (ex 1.x, 2.x, 3.x): Contain changes to data model/structure, as well as the data itself. Major versions will be released with significant advance notice.

For convenience, the date is also included in the release file name, ex: v1.0-2022-03-15-ror-data.zip.

Beginning with the 16 March 2023 release, a CSV file is included in addition to the canonical JSON. The CSV contains a subset of fields from the JSON file, some of which have been flattened for easier parsing. The JSON file remains the version of record.

The ROR data dump is provided under the [Creative Commons CC0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/). Location data in ROR comes from GeoNames and is licensed under a [Creative Commons Attribution 4.0 license](https://creativecommons.org/licenses/by/4.0/).

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/curation_ops/commit/81a40e9621796514f95116f8602bfeb0773d841a
