### ISSUE TITLE
[BUG] v2->v1 conversion removes Funder IDs from records

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#255]
**Version**
v2

**Describe the bug**
The v2->v1 conversion script is removing Funder IDs from records when converting from v2 to v1 format.

**To Reproduce**
1. Compare the following v2 and v1 record files for ROR ID 05mmh0f86:
   - v2 (release file): https://github.com/ror-community/ror-records/blob/ba8483eb8a8848d9dab634a0542a87e91d3dae5f/v1.45/05mmh0f86.json
   - v1 (converted): https://github.com/ror-community/ror-records/blob/ba8483eb8a8848d9dab634a0542a87e91d3dae5f/v1.45/v1/05mmh0f86.json
2. Observe that Funder IDs are present in the v2 file but missing in the v1 files committed after the conversion script is ran.
3. Compare the same record using the v1 and v2 versions of the API:
   - V1: https://api.ror.org/v1/organizations/05mmh0f86
   - V2: https://api.ror.org/v2/organizations/05mmh0f86 
5. Confirm that Funder IDs are missing in the v1 API response:

**Expected behavior**
Funder IDs should be preserved when converting from v2 to v1 format.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/curation_ops/commit/f9806a70a253f99ccb137a8b081a424815668ca4
