### ISSUE TITLE
[FEATURE] Display All/Multiple Locations in Site UI

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#262]
**Version**
v2

**Describe the problem you would like to solve**
With the release of v2 of our schema, multiple locations are being added to organizations but are not displayed in the UI. This creates potential confusion for users who may not see all locations by toggling to the API view. We have likewise received requests to display all, e.g. https://github.com/ror-community/ror-updates/issues/14076.

**Describe the solution you'd like**
Update the site UI to display multiple locations for organizations where these are present in the record. 

**Who would benefit from this feature?**
Users who need to identify that a record has multiple locations or that all locations are included on a record

**Comment by lizkrznarich** [comment]
@adambuttrick This was already included in the v2 UI updates, and this record does show 2 locations https://ror.org/011aa4g29 . Is there anything additional needed?

**Comment by adambuttrick** [comment]
Oh my bad, I forget we did this. All good!
