### ISSUE TITLE
Copy of the ROR id in my clipboard

### ISSUE THREAD

**Issue by annelhote** [ror-community/ror-roadmap#284]
As a user, I use https://ror.org/search to find the ROR of an organization. After my search (eg: https://ror.org/search?page=1&query=universit%C3%A9%20de%20lorraine) I would like to be able to copy the ROR id of that organization in my clipboard to use it anywhere else.

**Comment by adambuttrick** [comment]
Merging into https://github.com/ror-community/ror-roadmap/issues/269.
