### ISSUE TITLE
[BUG] Header for "Other Identifiers" is visible in record UI when no identifiers exist

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#37]
**Describe the bug**
The header for external IDs ("Other Identifiers") is displayed in the record UI when there are no such identifiers included in the record. 

**To Reproduce**
1. Identify an organization that has no external IDs ("Other Identifiers") (example: https://ror.org/01d74sk53, https://ror.org/02f4ks689)
2. Go to the organization's record in the search UI
3. Look at the "Other Identifiers" section

**Expected behavior**
If there are no external IDs associated with an organization, the "Other Identifiers" heading should not be visible in the record UI. Currently, it looks like information is missing because the heading is present but there is no information associated with it. 

**Screenshots**
![Screen Shot 2022-03-24 at 4 18 20 PM](https://user-images.githubusercontent.com/45110557/160025385-a11f29ea-b043-4a2c-89da-11dca611661a.png)

**Device information:**
 - Device type: Desktop, Phone
 - OS: macOS Catalina, iOS 15.4
 - Browser: Chrome, Safari, Firefox

**Additional context**
n/a

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-app/pull/76
