### ISSUE TITLE
[FEATURE] Displaying the relationship between organization 

### ISSUE THREAD

**Issue by Franziska-FZJ** [ror-community/ror-roadmap#46]
**Describe the problem you would like to solve**
The relationships between organizations (like parent institute, child institute) have been taken over from GRID, but are not yet displayed on the website. 

**Describe the solution you'd like**
If this information could be added to the general organization information, that would be great. A good way to do this is shown by GRID (see additional information).

**Who would benefit from this feature?**
It would help to identify organizations with common names through their relationships. It would also expand the possible use cases of ROR by providing a more detailed representation of complex reality. 
In several community workshops related to PIDs, participants have expressed the need to see relationships displayed. This feature would improve the re-uses of the ROR enormously.

**Additional information**
![grafik](https://user-images.githubusercontent.com/104140107/167108447-56427c57-f910-4cb2-88c7-edef02f11e64.png)

**Comment by mariagould** [comment]
Hello @Franziska-FZJ thank you for submitting this feedback. Relationships between organizations are exposed in the ROR API but as you note, these are not currently visible in the search UI. There are a few other pieces of metadata available in the API only at present, and we have been collecting input from users about use cases and preferences for adding additional metadata to the UI (see https://github.com/ror-community/ror-api/issues/157). 

I appreciate the comprehensive details you have provided above. I invite you to share any additional insights you have about specific use cases for viewing relationships in the UI. This will help us to think through some considerations around design and display of this information.

**Comment by adambuttrick** [comment]
Comment from John Lewis at Cambridge University Press about adding this feature:

"One of the major benefits of the grid website was its listing of "child" institutions which are attached to main institutions (or in fact, whether the record you were looking at was for an institution which is a child of a much bigger organisation). Separately, Grid also showed affiliated institutions, which are related in a tangential way to the institution, which you are viewing. This functionality enabled users to get all the IDs associated with an institution and then be able to add associated institutions if you wanted to. The "child" associations are extremely valuable especially for Open Access workflows for all academic publishers and although it is fantastic to have the grid IDs listed alongside the ROR IDs, without the child association listings there is a major functional data loss switching to ROR."

**Comment by lizkrznarich** [comment]
@Franziska-FZJ I happy to say that as of 1 Jul relationships are now displayed on ROR records, similar to the way they were displayed in GRID.
