### ISSUE TITLE
[BUG] Search UI does not display preferred external ID

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#51]
**Describe the bug**
When a record has multiple external IDs, one of them is indicated as the preferred ID. This information displays correctly in the API but the preferred ID is not always selected in the search UI. 

The issue affects records with multiple ISNI IDs or multiple Funder Registry IDs in which the preferred ID is not listed first in the "all" array. It appears that the code for the UI display defaults to displaying the first object from "all" for every external ID (https://github.com/ror-community/ror-app/blob/254540577a4e458d2e578dd3346e86bfc0446ad1/app/components/organization-item.js#L20)

**Example:**
In https://api.ror.org/organizations/https://ror.org/01vr20t27, ISNI ID `0000 0001 2109 5895` is marked as "preferred" but it appears second in the "all" array. In the the search UI, the ISNI ID displayed is `0000 0004 0428 8574`, which is listed first in the "all" array but not marked as preferred.

**To Reproduce**
1. Look up a record in the API that has multiple external IDs
2. Check which ID is marked as preferred in the API
3. Look up the record in the search UI
4. Check which ID appears in the search UI and compare whether it is the same as in the API

**Expected behavior**
If there is an external ID marked as preferred, it should be the one that displays in the search UI. If there is no external ID marked as preferred, the UI should default to the first ID listed in "all."

**Screenshots**
![Screen Shot 2022-06-20 at 10 35 08 AM](https://user-images.githubusercontent.com/45110557/174653814-0e674085-bca0-4dac-85c3-1f95682a52de.png)
![Screen Shot 2022-06-20 at 10 35 19 AM](https://user-images.githubusercontent.com/45110557/174653821-0b0d560b-0f32-40d7-b923-dde4af1238da.png)

**Device information:**
n/a

**Additional context**
n/a

**Comment by adambuttrick** [comment]
The following six records are affected by this issue:

- https://ror.org/03jasrp23
- https://ror.org/059dyrr28
- https://ror.org/01vr20t27
- https://ror.org/02ryfmr77
- https://ror.org/00097mb19
- https://ror.org/03wmf1y16

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-app/pull/76
