### ISSUE TITLE
[FEATURE] Add schema.org metadata

### ISSUE THREAD

**Issue by cpritcha** [ror-community/ror-roadmap#60]
**Describe the problem you would like to solve**

A lack of schema.org metadata to link to about ROR

**Describe the solution you'd like**

It would be great to have some schema.org metadata about ROR on either the home page or at identifiers.org. Accessible schema.org metadata would make it easier to access basic descriptive information about what a ROR is and to reference organizations with a ROR using [PropertyValue](https://schema.org/PropertyValue). As an example a valid JSON-LD PropertyValue for a DOI would be

```json
{
  "@id": "https://doi.org/10.5066/F7VX0DMQ",
  "@type": "PropertyValue",
  "propertyID": "https://registry.identifiers.org/registry/doi",
  "value": "doi:10.5066/F7VX0DMQ",
  "url": "https://doi.org/10.5066/F7VX0DMQ"
}
```

Taking a look at the [ISNI](https://registry.identifiers.org/registry/isni) at identifiers.org in the [Rich Results Test](https://search.google.com/test/rich-results/result/r%2Fdatasets?id=ezTW-SlfwbcnVF-30jbvzQ) you can see that it includes a description and a name.

An URL for propertyID is better than plain text because you can link to additional metadata.

**Who would benefit from this feature?**

Research catalogue creators, researchers harvesting metadata from research catalogues

**Additional Information**

Related Discussions and References
------------------------------------

- https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#identifier
- https://github.com/ORCID/ORCID-Source/issues/6520

**Comment by amandafrench** [comment]
Thanks for this, @cpritcha! Maria went ahead and requested a prefix for us at identifiers.org and ROR has a page there now at https://registry.identifiers.org/registry/ror

**Comment by cpritcha** [comment]
Great! Thanks! I'll close this issue then.
