### ISSUE TITLE
[MAINTENANCE] Remove https://ror.org/02r109517 from GRID Removed Records List

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#72]
**Service/repository**
ROR API
**Describe the current state/issue**
https://ror.org/02r109517 is currently included [in the set of GRID removed records](https://github.com/ror-community/ror-api/blob/bd040a0d2558a478c06a89118a29eeb9b6142710/rorapi/settings.py#L300).

**Describe the desired state/solution**
In release v1.5, this ROR ID will be added back the registry. It should therefore be removed from the list so it can be returned properly in the API.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-api/pull/272
