### ISSUE TITLE
Duplicate FundRef

### ISSUE THREAD

**Issue by AlexeyBMJ** [ror-community/ror-roadmap#74]
A duplicate FundRef value appeared in response to the following API request recently:
https://api.ror.org/organizations/052tfza37
...
        "FundRef": {
            "preferred": "100005563",
            "all": [
                "100008199",
                **"100005563",
                "100005563"**
            ]
        },
...

We've never discovered a duplicate FundRef value in ROR data before so we are treating this as a bug in the ROR source data.

**Comment by adambuttrick** [comment]
@AlexeyBMJ Apologies for that. We will fix shortly. Please follow the issue here to be notified when this has been corrected.

https://github.com/ror-community/ror-updates/issues/1043

**Comment by adambuttrick** [comment]
This has been fixed.

**Comment by AlexeyBMJ** [comment]
Brilliant! Thank you
