### ISSUE TITLE
[BUG] The data-dump version-specific Zenodo dataset also contains previous data-dump files

### ISSUE THREAD

**Issue by paulmillar** [ror-community/ror-roadmap#76]
**Describe the bug**

When looking at the Zenodo page for the data-dump (e.g., [doi:10.5281/zenodo.6347574](https://doi.org/10.5281/zenodo.6347574) for the latest version), the `Files` section contains not only the latest version of the data dump (a zip file), but also all previous versions (each as a zip file).

For example, v1.5 ([doi:10.5281/zenodo.7038913](https://doi.org/10.5281/zenodo.7038913)) currently lists the following files:
- `v1.0-2022-03-17-ror-data.json.zip`
- `v1.1-2022-06-16-ror-data.zip`
- `v1.2-2022-06-27-ror-data.zip`
- `v1.3-2022-08-03-ror-data.zip`
- `v1.4-2022-08-16-ror-data.zip`
- `v1.5-2022-08-31-ror-data.zip`

Note that each version of the data-dump has its own specific Zenodo dataset, and each of these Zenodo datasets has its own unique DOI.  This above example Zenodo dataset (`doi:10.5281/zenodo.7038913`) is specifically v1.5.  Therefore, the listed files are _all_ associated with this v1.5-specific Zenodo dataset.

Including previous versions (of the data dump) in addition to the dataset's specific version is problematic because it becomes hard to download (automatically) the desired data-dump version.  The client is required to parse the filename of each zip file to extract the version information (e.g., `v1.5-2022-08-31-ror-data.zip` --> 1.5), sort the available versions (taking into account the adopted semantic versioning scheme) and select the most recent version.

This may also confuse people, as Zenodo will present them with a list of files, while the user is expecting a single zip file.

Including all the files also (seemingly) confuses Zenodo itself.  By default, the `Preview` box shows the first file from the dataset's list.  Currently, this seems always to be the oldest release (`v1.0-2022-03-17-ror-data.json.zip`).  Therefore, when first viewing the v1.5 Zenodo dataset (for example), the user is presented with the "wrong" (v1.0) contents in the Preview box.

Note that Zenodo provides a `Versions` dialogue box (on the right-hand side of the page) that allows people to easily navigate between different versions of the "ROR Data" dataset, should someone want to download a specific version.  Therefore, including all previous data-dump files in a Zenodo dataset provides no benefit

**To Reproduce**
1. Navigate to [the most recent version](https://doi.org/10.5281/zenodo.6347574)
2. Scroll down to the `Files` section
3. Observe the list of available files for download.

**Expected behavior**

I would expect the `Files` section of the Zenodo page for the v1.5 of the data dump ([doi:10.5281/zenodo.7038913](https://doi.org/10.5281/zenodo.7038913)) to list a single file: `v1.5-2022-08-31-ror-data.zip`.

I would expect the `Files` section of the Zenodo page for v1.4 of the data dump [doi:10.5281/zenodo.7004824](https://doi.org/10.5281/zenodo.7004824) to list the single file `v1.4-2022-08-16-ror-data.zip`.

In general, I would expect the Zenodo page for any version of the data dump to show a single zip file that contains that specific version of the data dump.
.

**Comment by mariagould** [comment]
Hi @paulmillar thank you for sharing this feedback. This is not really a bug but rather a function of the practices we have had in place for publishing new data dumps. We acknowledge that including all of the previous files can cause some confusion and is not necessary or beneficial. Starting with the next data dump (coming soon), we will only include a single file. Thank you again for your feedback!

**Comment by mariagould** [comment]
Hi @paulmillar I just wanted to confirm that in our latest data dump, published yesterday (https://doi.org/10.5281/zenodo.7126390.), we began following the practice of removing the previously uploaded files. We also retroactively removed the additional files from previous data dumps, so all data dump versions since v1.0 now have a single file. Thanks again for suggesting this improvement!

**Comment by paulmillar** [comment]
Many thanks!
