### ISSUE TITLE
[BUG] Leo - Removing all external IDs does not remove field

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#78]
**Describe the bug**
When all external IDs for a given external ID field are removed in Leo, the field itself is still preserved in the record, when it should be deleted.

**To Reproduce**
1. Go to a record containing an external ID
2. Delete external ID values from both the preferred and all fields.
3. Download record.
4. Record contains the external ID field without any values.

**Expected behavior**
Field is deleted from record when all values are removed.

**Screenshots**

<img width="500" alt="Screen Shot 2022-09-07 at 3 37 04 PM" src="https://user-images.githubusercontent.com/5152876/188995668-8319d658-935b-4ec8-b185-bd2c8f822777.png">

**Device information:**
 - Device type: Laptop
 - OS: MacOS v12.5.1
 - Browser: Firefox
 - Version: 104.0.2 

**Additional context**

**Comment by lizkrznarich** [comment]
Closing because leo will be discontinued in 2023
