### ISSUE TITLE
[BUG] Leo increments years in "Established" field in intervals of .1

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-roadmap#80]
**Describe the bug**
Leo increments years in "Established" field in intervals of .1

**To Reproduce**
1. Go to https://leo.dev.ror.org
2. Click on "NEW RECORD"
3. Enter a year value in the "Established field"
4. Use arrow next to field to increment value
5. Value increases by .1 until reaching next whole number.

**Expected behavior**
Year is incremented by 1 instead of .1.

**Screenshots**
<img width="594" alt="Screen Shot 2022-09-13 at 3 27 05 PM" src="https://user-images.githubusercontent.com/5152876/190020311-63882f27-e1b2-4450-a872-7613e97ea621.png">

**Device information:**
 - Device type: Laptop
 - OS: MacOS 12.6
 - Browser: Firefox
 - Version: 104.0.2

**Comment by lizkrznarich** [comment]
Closing because leo will be discontinued in 2023
