### ISSUE TITLE
[ROADMAP] Update data model/schema

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#9]
**Description:** 
The current ROR data model/schema was inherited from GRID. Now that ROR is officially independent of GRID, there are some changes we want to make to the existing data structure to optimize its usability and incorporate community feedback. 

**Specific work related to this roadmap item:**
- https://github.com/ror-community/ror-roadmap/issues/6
- https://github.com/ror-community/ror-api/issues/183
- https://github.com/ror-community/ror-api/issues/53
- https://github.com/ror-community/ror-api/issues/57
- https://github.com/ror-community/ror-api/issues/144
- https://github.com/ror-community/ror-api/issues/80

**Comment by lizkrznarich** [comment]
Schema changes were developed in consultation with the ROR community Dec 2022-Mar 2023. The final proposal is available at https://docs.google.com/document/d/18Qg6-lv2Fxkc97SLpD8gdS0V8p0y9fdaZEywyeyKJWM
